### ISSUE TITLE
`web` docker image doesn't run

### ISSUE THREAD

**Issue by santanaluiz** [rootstrap/rails_api_base#599]
## Bug report:
* **Expected Behavior**: all the 3 images should run fine
* **Actual Behavior**: `web` docker compose image doesn't run
* **Steps to Reproduce**: 
  1. Clone project
  2. Run `bootstrap` script
  3. See image failing

* **Version of the repo**: head
* **Ruby and Rails Version**: 7.0.8
* **Rails Stacktrace**: 

Docker logs:

```
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:14: [BUG] Segmentation fault at 0x0052ffff7f5506c0
2024-01-16 20:22:32 ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [aarch64-linux]
2024-01-16 20:22:32 
2024-01-16 20:22:32 -- Control frame information -----------------------------------------------
2024-01-16 20:22:32 c:0061 p:---- s:0335 e:000334 CFUNC  :resume
2024-01-16 20:22:32 c:0060 p:0007 s:0331 E:001400 BLOCK  /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:14 [FINISH]
2024-01-16 20:22:32 c:0059 p:---- s:0328 e:000327 CFUNC  :synchronize
2024-01-16 20:22:32 c:0058 p:0026 s:0324 E:0009d8 METHOD /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:12
2024-01-16 20:22:32 c:0057 p:0007 s:0319 e:000318 CLASS  /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:18
2024-01-16 20:22:32 c:0056 p:0025 s:0316 e:000315 TOP    /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:5 [FINISH]
2024-01-16 20:22:32 c:0055 p:---- s:0313 e:000312 CFUNC  :require
2024-01-16 20:22:32 c:0054 p:0030 s:0308 e:000307 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0053 p:0158 s:0302 e:000301 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0052 p:0041 s:0292 e:000291 TOP    /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/reentrant_read_write_lock.rb:7 [FINISH]
2024-01-16 20:22:32 c:0051 p:---- s:0289 e:000288 CFUNC  :require
2024-01-16 20:22:32 c:0050 p:0030 s:0284 e:000283 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0049 p:0158 s:0278 e:000277 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0048 p:0047 s:0268 e:000267 TOP    /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomics.rb:8 [FINISH]
2024-01-16 20:22:32 c:0047 p:---- s:0265 e:000264 CFUNC  :require
2024-01-16 20:22:32 c:0046 p:0030 s:0260 e:000259 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0045 p:0158 s:0254 e:000253 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0044 p:0029 s:0244 e:000243 TOP    /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent.rb:6 [FINISH]
2024-01-16 20:22:32 c:0043 p:---- s:0241 e:000240 CFUNC  :require
2024-01-16 20:22:32 c:0042 p:0030 s:0236 e:000235 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0041 p:0158 s:0230 e:000229 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0040 p:0017 s:0220 e:000219 TOP    /src/bundle/gems/activesupport-7.0.8/lib/active_support/logger_thread_safe_level.rb:5 [FINISH]
2024-01-16 20:22:32 c:0039 p:---- s:0217 e:000216 CFUNC  :require
2024-01-16 20:22:32 c:0038 p:0030 s:0212 e:000211 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0037 p:0158 s:0206 e:000205 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0036 p:0017 s:0196 e:000195 TOP    /src/bundle/gems/activesupport-7.0.8/lib/active_support/logger_silence.rb:5 [FINISH]
2024-01-16 20:22:32 c:0035 p:---- s:0193 e:000192 CFUNC  :require
2024-01-16 20:22:32 c:0034 p:0030 s:0188 e:000187 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0033 p:0158 s:0182 e:000181 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0032 p:0005 s:0172 e:000171 TOP    /src/bundle/gems/activesupport-7.0.8/lib/active_support/logger.rb:3 [FINISH]
2024-01-16 20:22:32 c:0031 p:---- s:0169 e:000168 CFUNC  :require
2024-01-16 20:22:32 c:0030 p:0030 s:0164 e:000163 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0029 p:0158 s:0158 e:000157 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0028 p:0023 s:0148 e:000147 TOP    /src/bundle/gems/activesupport-7.0.8/lib/active_support.rb:29 [FINISH]
2024-01-16 20:22:32 c:0027 p:---- s:0145 e:000144 CFUNC  :require
2024-01-16 20:22:32 c:0026 p:0030 s:0140 e:000139 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0025 p:0158 s:0134 e:000133 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0024 p:0005 s:0124 e:000123 TOP    /src/bundle/gems/railties-7.0.8/lib/rails/command.rb:3 [FINISH]
2024-01-16 20:22:32 c:0023 p:---- s:0121 e:000120 CFUNC  :require
2024-01-16 20:22:32 c:0022 p:0030 s:0116 e:000115 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0021 p:0158 s:0110 e:000109 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0020 p:0005 s:0100 e:000099 TOP    /src/bundle/gems/railties-7.0.8/lib/rails/commands.rb:3 [FINISH]
2024-01-16 20:22:32 c:0019 p:---- s:0095 e:000094 CFUNC  :require
2024-01-16 20:22:32 c:0018 p:0030 s:0090 e:000089 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0017 p:0158 s:0084 e:000083 METHOD /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
2024-01-16 20:22:32 c:0016 p:0074 s:0074 e:000073 TOP    /src/myapp/bin/rails:12 [FINISH]
2024-01-16 20:22:32 c:0015 p:---- s:0071 e:000070 CFUNC  :load
2024-01-16 20:22:32 c:0014 p:0120 s:0066 e:000065 METHOD /src/bundle/gems/spring-4.1.3/lib/spring/client/rails.rb:28
2024-01-16 20:22:32 c:0013 p:0007 s:0061 e:000060 METHOD /src/bundle/gems/spring-4.1.3/lib/spring/client/command.rb:7
2024-01-16 20:22:32 c:0012 p:0011 s:0056 e:000055 METHOD /src/bundle/gems/spring-4.1.3/lib/spring/client.rb:30
2024-01-16 20:22:32 c:0011 p:0194 s:0050 e:000049 TOP    /src/bundle/gems/spring-4.1.3/bin/spring:49 [FINISH]
2024-01-16 20:22:32 c:0010 p:---- s:0044 e:000043 CFUNC  :load
2024-01-16 20:22:32 c:0009 p:0083 s:0039 e:000038 TOP    /src/bundle/gems/spring-4.1.3/lib/spring/binstub.rb:11 [FINISH]
2024-01-16 20:22:32 c:0008 p:---- s:0033 e:000032 CFUNC  :require
2024-01-16 20:22:32 c:0007 p:0030 s:0028 e:000027 BLOCK  /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74
2024-01-16 20:22:32 c:0006 p:0037 s:0022 e:000021 BLOCK  /src/myapp/bin/spring:10
2024-01-16 20:22:32 c:0005 p:0003 s:0018 e:000017 METHOD <internal:kernel>:90
2024-01-16 20:22:32 c:0004 p:0058 s:0014 e:000013 TOP    /src/myapp/bin/spring:7 [FINISH]
2024-01-16 20:22:32 c:0003 p:---- s:0011 e:000010 CFUNC  :load
2024-01-16 20:22:32 c:0002 p:0049 s:0006 e:000005 EVAL   bin/rails:9 [FINISH]
2024-01-16 20:22:32 c:0001 p:0000 s:0003 E:0018d0 DUMMY  [FINISH]
2024-01-16 20:22:32 
2024-01-16 20:22:32 -- Ruby level backtrace information ----------------------------------------
2024-01-16 20:22:32 bin/rails:9:in `<main>'
2024-01-16 20:22:32 bin/rails:9:in `load'
2024-01-16 20:22:32 /src/myapp/bin/spring:7:in `<top (required)>'
2024-01-16 20:22:32 <internal:kernel>:90:in `tap'
2024-01-16 20:22:32 /src/myapp/bin/spring:10:in `block in <top (required)>'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/spring-4.1.3/lib/spring/binstub.rb:11:in `<top (required)>'
2024-01-16 20:22:32 /src/bundle/gems/spring-4.1.3/lib/spring/binstub.rb:11:in `load'
2024-01-16 20:22:32 /src/bundle/gems/spring-4.1.3/bin/spring:49:in `<top (required)>'
2024-01-16 20:22:32 /src/bundle/gems/spring-4.1.3/lib/spring/client.rb:30:in `run'
2024-01-16 20:22:32 /src/bundle/gems/spring-4.1.3/lib/spring/client/command.rb:7:in `call'
2024-01-16 20:22:32 /src/bundle/gems/spring-4.1.3/lib/spring/client/rails.rb:28:in `call'
2024-01-16 20:22:32 /src/bundle/gems/spring-4.1.3/lib/spring/client/rails.rb:28:in `load'
2024-01-16 20:22:32 /src/myapp/bin/rails:12:in `<top (required)>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/railties-7.0.8/lib/rails/commands.rb:3:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/railties-7.0.8/lib/rails/command.rb:3:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/activesupport-7.0.8/lib/active_support.rb:29:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/activesupport-7.0.8/lib/active_support/logger.rb:3:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/activesupport-7.0.8/lib/active_support/logger_silence.rb:5:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/activesupport-7.0.8/lib/active_support/logger_thread_safe_level.rb:5:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent.rb:6:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomics.rb:8:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/reentrant_read_write_lock.rb:7:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
2024-01-16 20:22:32 /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:5:in `<main>'
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:18:in `<module:Concurrent>'
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:12:in `mutex_owned_per_thread?'
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:12:in `synchronize'
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:14:in `block in mutex_owned_per_thread?'
2024-01-16 20:22:32 /src/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/lock_local_var.rb:14:in `resume'
2024-01-16 20:22:32 
2024-01-16 20:22:32 -- Threading information ---------------------------------------------------
2024-01-16 20:22:32 Total ractor count: 1
2024-01-16 20:22:32 Ruby thread count for this ractor: 1
2024-01-16 20:22:32 
2024-01-16 20:22:32 -- Machine register context ------------------------------------------------
2024-01-16 20:22:32   x0: 0x0000aaaaf1ccfb50  x1: 0x0000aaaaf2a55d60  x2: 0x0000ffffe80d76e0
2024-01-16 20:22:32   x3: 0x0000ffff6524ff60  x4: 0x0000ffff65250018  x5: 0x0000ffff65270000
2024-01-16 20:22:32   x6: 0x0000ffff7faa0b88  x7: 0x0000000000000000 x18: 0x0000000000000000
2024-01-16 20:22:32  x19: 0x0000000000000000 x20: 0x0000000000000000 x21: 0x0000000000000000
2024-01-16 20:22:32  x22: 0x0000000000000000 x23: 0x0000000000000000 x24: 0x0000000000000000
2024-01-16 20:22:32  x25: 0x0000000000000000 x26: 0x0000000000000000 x27: 0x0000000000000000
2024-01-16 20:22:32  x28: 0x0000000000000000 x29: 0x0000000000000000  sp: 0x0000ffff65250000
2024-01-16 20:22:32  fau: 0x0052ffff7f5506c0
2024-01-16 20:22:32 
2024-01-16 20:22:32 -- C level backtrace information -------------------------------------------

```

**Comment by santanaluiz** [comment]
Side note: I can run `bin/dev` and rspec runs fine if headless

**Comment by santanaluiz** [comment]
Downgrading to Ruby 3.2 indeed fixed.\
Thanks!

Another Q: 

The README mentions:\
> Generate a secret key for the app by running bin/web rails secret, copy it and add it in your environment variables.

But it doesn't mention what is actually the variable name 🤔

**Comment by santib** [comment]
It refers to the [SECRET_KEY_BASE](https://api.rubyonrails.org/classes/Rails/Application.html#method-i-secret_key_base).

But now that you mention I don't think it's needed at all. Do you want to confirm it by testing that the app works without it, and make a PR fixing the README?

**Comment by santanaluiz** [comment]
actually, rspec fails without it. But I updated the docker-compose file and added a few notes in the README. 

PR is open.

Thanks!
